// Auth
export const LOADED = 'LOADED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// Register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

// Notifications
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

// Forgot Password
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'
export const FORGOT_PASSWORD_LOADING = 'FORGOT_PASSWORD_LOADING'

// Reset Password
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
export const RESET_PASSWORD_GET_USER_SUCCESS = 'RESET_PASSWORD_GET_USER_SUCCESS'
export const RESET_PASSWORD_GET_USER_FAIL = 'RESET_PASSWORD_GET_USER_FAIL'

// onBoarding
export const ON_BOARDING_SUCCESS = 'ON_BOARDING_SUCCESS'
export const ON_BOARDING_FAILT = 'ON_BOARDING_FAILT'

// Last Pokemons
export const LAST_POKEMONS_LOADED = 'LAST_POKEMONS_LOADED'
export const LAST_POKEMONS_FAILT = 'LAST_POKEMONS_FAILT'
